### ISSUE TITLE
GSI GLOBAL nemsio T1534 berror

### ISSUE THREAD

**Issue by colechan** [comgsi/GSI#5]
Dear helper:
       Recently I am using GSI V3.7 to perform global assimilation of GFS's nemsio format T1536. I can now read the nemsio data into the assimilation system, but GSI always displays this mistake when dealing with global background error covariance. 
![image](https://user-images.githubusercontent.com/43697007/100712696-20c5d080-33ee-11eb-88a6-79e30e0d7c3b.png)

      I would like to ask if there is an error caused by the global background error covariance of the corresponding resolution in GSI/fix/Big_Endian! The attachment is my stdout! If this is the reason, can I ask where you can get the file of global_berror.l64y1538.f77! Looking forward to your reply!

**Comment by guoqing-noaa** [comment]
We don't have global_berror.l64y1538.f77.  NOAA GFS operation does GSI analyses at the T574 resolution.

**Comment by colechan** [comment]
I wanna ask how u do T1538 to T574

**Comment by guoqing-noaa** [comment]
It is encouraged to ask GSI/EnKF related questions at the GSI/EnKF forum:
https://www.dtcenter.org/forum/gsi-enkf-user-support
Thanks!
